name: UDJWebClient
version: 0.0.1
description: >
  A web client for UDJ
authors:
 - Reed La Botz <reedlabotz@gmail.com>
 - J. Taylor Fairbank <jtfairbank@gmail.com>
homepage: https://github.com/UDJ/udj-webclient-dart
dependencies:
  browser: any
  js:
    hosted: js
  web_ui: any