name: UDJWebClient
description: >
    A web client for UDJ
version: 0.0.1
author: Reed La Botz <reedlabotz@gmail.com>
homepage: https://github.com/reedlabotz/udj-webclient
dependencies:
  browser: any
  js:
    hosted: js